// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/addresses": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a list of all addresses.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networking",
                    "addresses"
                ],
                "summary": "List Addresses",
                "responses": {
                    "200": {
                        "description": "List of addresses",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/sentinelos_core_internal_model.Address"
                            }
                        }
                    },
                    "500": {
                        "description": "ERR_SYS_4001 Internal server error",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new address object.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networking",
                    "addresses"
                ],
                "summary": "Create Address",
                "parameters": [
                    {
                        "description": "Address details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.AddressCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: address created in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "ERR_NET_1004 Invalid JSON or Missing field",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "409": {
                        "description": "ERR_NET_2006 Resource already exists",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/addresses/{name}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing address object.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networking",
                    "addresses"
                ],
                "summary": "Edit Address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Address Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Address details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.AddressEditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: address updated in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or Missing field",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "404": {
                        "description": "ERR_NET_1003 Resource not found",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete an existing address object.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networking",
                    "addresses"
                ],
                "summary": "Delete Address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Address Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: address deleted from candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing required field",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "404": {
                        "description": "ERR_NET_1003 Resource not found",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/config/begin": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Start a new candidate configuration session.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system",
                    "config"
                ],
                "summary": "Begin Configuration Session",
                "responses": {
                    "200": {
                        "description": "message: config session started",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Missing authorization token",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "409": {
                        "description": "Config session already active",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/config/commit": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Commit the candidate configuration to running configuration.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system",
                    "config"
                ],
                "summary": "Commit Configuration",
                "responses": {
                    "200": {
                        "description": "message: commit successful",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Commit error",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/dhcp": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a list of all DHCP configurations.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networking",
                    "dhcp"
                ],
                "summary": "List DHCP Configs",
                "responses": {
                    "200": {
                        "description": "List of DHCP configs",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/sentinelos_core_internal_model.DHCP"
                            }
                        }
                    },
                    "500": {
                        "description": "ERR_SYS_4001 Internal server error",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new DHCP configuration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networking",
                    "dhcp"
                ],
                "summary": "Create DHCP Config",
                "parameters": [
                    {
                        "description": "DHCP details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.DhcpCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: dhcp pool created in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/dhcp/{interface}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing DHCP configuration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networking",
                    "dhcp"
                ],
                "summary": "Edit DHCP Config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Interface Name",
                        "name": "interface",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "DHCP details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.DhcpEditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: dhcp pool updated in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or Missing field",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "404": {
                        "description": "ERR_NET_1003 Resource not found",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete an existing DHCP configuration.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networking",
                    "dhcp"
                ],
                "summary": "Delete DHCP Config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Interface Name",
                        "name": "interface",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: dhcp pool deleted in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing required field",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "404": {
                        "description": "ERR_NET_1003 Resource not found",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/interfaces": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a list of all network interfaces.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networking",
                    "interfaces"
                ],
                "summary": "List Interfaces",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by OSI layer (2 or 3)",
                        "name": "layer",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of interfaces",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/sentinelos_core_internal_system.InterfaceInfo"
                            }
                        }
                    },
                    "500": {
                        "description": "ERR_SYS_4001 Internal server error",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/interfaces/{name}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing network interface.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networking",
                    "interfaces"
                ],
                "summary": "Edit Interface",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Interface Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Interface details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.InterfaceEditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: interface updated in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or Zone does not exist",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "404": {
                        "description": "ERR_NET_1003 Resource not found",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "description": "Authenticate an admin and receive a JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "Admin Login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful login",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "ERR_NET_1004 Invalid JSON",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "401": {
                        "description": "ERR_SEC_5005 Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "405": {
                        "description": "ERR_NET_1009 Method not allowed",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "500": {
                        "description": "ERR_SEC_5006 Failed to generate token",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/me": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get current authenticated user details.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Current User",
                "responses": {
                    "200": {
                        "description": "User details",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Missing authorization token",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/nat": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a list of all NAT rules.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security",
                    "nat"
                ],
                "summary": "List NAT Rules",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by NAT type (e.g. snat, dnat-ip)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of NAT rules",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/sentinelos_core_internal_model.NATRule"
                            }
                        }
                    },
                    "500": {
                        "description": "ERR_SYS_4001 Internal server error",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new NAT rule.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security",
                    "nat"
                ],
                "summary": "Create NAT Rule",
                "parameters": [
                    {
                        "description": "NAT details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.NatCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: NAT rule added in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or NAT type",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/nat/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing NAT rule.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security",
                    "nat"
                ],
                "summary": "Edit NAT Rule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "NAT Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "NAT details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.NatEditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: NAT rule updated in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or ID",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "404": {
                        "description": "ERR_NET_1003 Resource not found",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete an existing NAT rule.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security",
                    "nat"
                ],
                "summary": "Delete NAT Rule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "NAT Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: NAT rule deleted in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "404": {
                        "description": "ERR_NET_1003 Resource not found",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/nat/{id}/move": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Move a NAT rule relative to another rule (top, bottom, before, after).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security",
                    "nat"
                ],
                "summary": "Move NAT Rule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "NAT Rule ID to move",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Move details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.NatMoveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: NAT rule moved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or Position",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "404": {
                        "description": "ERR_NET_1003 NAT Rule not found",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/policies": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a list of all policies.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security",
                    "policies"
                ],
                "summary": "List Policies",
                "responses": {
                    "200": {
                        "description": "List of policies",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/sentinelos_core_internal_model.Policy"
                            }
                        }
                    },
                    "500": {
                        "description": "ERR_SYS_4001 Internal server error",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new security policy.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security",
                    "policies"
                ],
                "summary": "Create Policy",
                "parameters": [
                    {
                        "description": "Policy details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.PolicyCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: policy created in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or references unknown entity",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/policies/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing security policy.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security",
                    "policies"
                ],
                "summary": "Edit Policy",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Policy ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Policy details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.PolicyEditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: policy updated in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or ID",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "404": {
                        "description": "ERR_NET_1003 Resource not found",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete an existing security policy.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security",
                    "policies"
                ],
                "summary": "Delete Policy",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Policy ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: policy deleted from candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "404": {
                        "description": "ERR_NET_1003 Resource not found",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/policies/{id}/move": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Move a policy relative to another policy (top, bottom, before, after).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security",
                    "policies"
                ],
                "summary": "Move Policy",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Policy ID to move",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Move details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.PolicyMoveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: policy moved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or Position",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "404": {
                        "description": "ERR_NET_1003 Policy not found",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/routes": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a list of all routes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networking",
                    "routes"
                ],
                "summary": "List Routes",
                "responses": {
                    "200": {
                        "description": "List of routes",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/sentinelos_core_internal_model.Route"
                            }
                        }
                    },
                    "500": {
                        "description": "ERR_SYS_4001 Internal server error",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new route object.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networking",
                    "routes"
                ],
                "summary": "Create Route",
                "parameters": [
                    {
                        "description": "Route details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.RouteCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: route created in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/routes/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing route object.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networking",
                    "routes"
                ],
                "summary": "Edit Route",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Route ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Route details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.RouteEditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: route updated in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or missing ID",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "404": {
                        "description": "ERR_NET_1003 Resource not found",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete an existing route object.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networking",
                    "routes"
                ],
                "summary": "Delete Route",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Route ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: route deleted from candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid or missing ID",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "404": {
                        "description": "ERR_NET_1003 Resource not found",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/services": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a list of all services.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security",
                    "services"
                ],
                "summary": "List Services",
                "responses": {
                    "200": {
                        "description": "List of services",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/sentinelos_core_internal_model.Service"
                            }
                        }
                    },
                    "500": {
                        "description": "ERR_SYS_4001 Internal server error",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new service object.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security",
                    "services"
                ],
                "summary": "Create Service",
                "parameters": [
                    {
                        "description": "Service details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ServiceCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: service created in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or protocol",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "409": {
                        "description": "ERR_NET_2006 Resource already exists",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/services/{name}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing service object.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security",
                    "services"
                ],
                "summary": "Edit Service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Service details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ServiceEditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: service updated in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or protocol",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "404": {
                        "description": "ERR_NET_1003 Resource not found",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete an existing service object.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security",
                    "services"
                ],
                "summary": "Delete Service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: service deleted from candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "ERR_NET_1003 Resource not found",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/status": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get the system and firewall status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Firewall Status",
                "responses": {
                    "200": {
                        "description": "Status details",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/vlans": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a list of all vlans.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networking",
                    "vlans"
                ],
                "summary": "List Vlans",
                "responses": {
                    "200": {
                        "description": "List of vlans",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/sentinelos_core_internal_model.Vlan"
                            }
                        }
                    },
                    "500": {
                        "description": "ERR_SYS_4001 Internal server error",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new vlan object.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networking",
                    "vlans"
                ],
                "summary": "Create Vlan",
                "parameters": [
                    {
                        "description": "Vlan details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.VlanCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: vlan created in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or Zone does not exist",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/vlans/{name}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing vlan object.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networking",
                    "vlans"
                ],
                "summary": "Edit Vlan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vlan Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Vlan details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.VlanEditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: vlan updated in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or Zone does not exist",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "404": {
                        "description": "ERR_NET_1003 Resource not found",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete an existing vlan object.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networking",
                    "vlans"
                ],
                "summary": "Delete Vlan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vlan Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: vlan deleted from candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "ERR_NET_1003 Resource not found",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/zones": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a list of all zones.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security",
                    "zones"
                ],
                "summary": "List Zones",
                "responses": {
                    "200": {
                        "description": "List of zones",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/sentinelos_core_internal_model.Zone"
                            }
                        }
                    },
                    "500": {
                        "description": "ERR_SYS_4001 Internal server error",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new zone object.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security",
                    "zones"
                ],
                "summary": "Create Zone",
                "parameters": [
                    {
                        "description": "Zone details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ZoneCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: zone added in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or Zone Type",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "409": {
                        "description": "ERR_NET_2006 Resource already exists",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/zones/{name}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing zone object.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security",
                    "zones"
                ],
                "summary": "Edit Zone",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Zone Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Zone details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ZoneEditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: zone updated in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or Zone Type",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    },
                    "404": {
                        "description": "ERR_NET_1003 Resource not found",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete an existing zone object.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "security",
                    "zones"
                ],
                "summary": "Delete Zone",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Zone Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: zone deleted in candidate",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "ERR_NET_1003 Resource not found",
                        "schema": {
                            "$ref": "#/definitions/sentinelos_core_pkg_utils.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_api_handlers.AddressCreateRequest": {
            "type": "object",
            "properties": {
                "ips": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.AddressEditRequest": {
            "type": "object",
            "properties": {
                "ips": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_api_handlers.DhcpCreateRequest": {
            "type": "object",
            "properties": {
                "dns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "end_ip": {
                    "type": "string"
                },
                "gateway": {
                    "type": "string"
                },
                "interface": {
                    "type": "string"
                },
                "lease_time": {
                    "type": "integer"
                },
                "start_ip": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.DhcpEditRequest": {
            "type": "object",
            "properties": {
                "dns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "end_ip": {
                    "type": "string"
                },
                "gateway": {
                    "type": "string"
                },
                "lease_time": {
                    "type": "integer"
                },
                "start_ip": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.InterfaceEditRequest": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string"
                },
                "management": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "state": {
                    "type": "string"
                },
                "zone": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.LoginResponse": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.NatCreateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "dst-addr": {
                    "type": "string"
                },
                "dst-zone": {
                    "type": "string"
                },
                "out-interface": {
                    "type": "string"
                },
                "service": {
                    "type": "string"
                },
                "src-addr": {
                    "type": "string"
                },
                "src-zone": {
                    "type": "string"
                },
                "translated-ip": {
                    "type": "string"
                },
                "translated-port": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.NatEditRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "dst-addr": {
                    "type": "string"
                },
                "dst-zone": {
                    "type": "string"
                },
                "out-interface": {
                    "type": "string"
                },
                "service": {
                    "type": "string"
                },
                "src-addr": {
                    "type": "string"
                },
                "src-zone": {
                    "type": "string"
                },
                "translated-ip": {
                    "type": "string"
                },
                "translated-port": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.NatMoveRequest": {
            "type": "object",
            "properties": {
                "position": {
                    "type": "string"
                },
                "reference_id": {
                    "type": "integer"
                }
            }
        },
        "internal_api_handlers.PolicyCreateRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "dst-addr": {
                    "type": "string"
                },
                "dst-zone": {
                    "type": "string"
                },
                "log": {
                    "type": "boolean"
                },
                "services": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "src-addr": {
                    "type": "string"
                },
                "src-zone": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.PolicyEditRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "dst-addr": {
                    "type": "string"
                },
                "dst-zone": {
                    "type": "string"
                },
                "log": {
                    "type": "boolean"
                },
                "services": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "src-addr": {
                    "type": "string"
                },
                "src-zone": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.PolicyMoveRequest": {
            "type": "object",
            "properties": {
                "position": {
                    "type": "string"
                },
                "reference_id": {
                    "type": "integer"
                }
            }
        },
        "internal_api_handlers.RouteCreateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "gateway": {
                    "type": "string"
                },
                "interface": {
                    "type": "string"
                },
                "metric": {
                    "type": "integer"
                }
            }
        },
        "internal_api_handlers.RouteEditRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "gateway": {
                    "type": "string"
                },
                "interface": {
                    "type": "string"
                },
                "metric": {
                    "type": "integer"
                }
            }
        },
        "internal_api_handlers.ServiceCreateRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "ports": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "protocol": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.ServiceEditRequest": {
            "type": "object",
            "properties": {
                "ports": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "protocol": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.VlanCreateRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "ip": {
                    "type": "string"
                },
                "management": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "parent": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "zone": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.VlanEditRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "ip": {
                    "type": "string"
                },
                "management": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "parent": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "zone": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.ZoneCreateRequest": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "interfaces": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "networks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.ZoneEditRequest": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "interfaces": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "networks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "net.IPNet": {
            "type": "object",
            "properties": {
                "ip": {
                    "description": "network number",
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "int32"
                    }
                },
                "mask": {
                    "description": "network mask",
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "int32"
                    }
                }
            }
        },
        "sentinelos_core_internal_model.Action": {
            "type": "string",
            "enum": [
                "allow",
                "deny"
            ],
            "x-enum-varnames": [
                "Allow",
                "Deny"
            ]
        },
        "sentinelos_core_internal_model.Address": {
            "type": "object",
            "properties": {
                "ips": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/net.IPNet"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "sentinelos_core_internal_model.DHCP": {
            "type": "object",
            "properties": {
                "dns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "endIP": {
                    "type": "string"
                },
                "gateway": {
                    "type": "string"
                },
                "interface": {
                    "type": "string"
                },
                "leaseTimeMin": {
                    "type": "integer"
                },
                "startIP": {
                    "type": "string"
                },
                "subnetMask": {
                    "type": "string"
                }
            }
        },
        "sentinelos_core_internal_model.NATRule": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "dstAddress": {
                    "type": "string"
                },
                "dstZone": {
                    "$ref": "#/definitions/sentinelos_core_internal_model.Zone"
                },
                "id": {
                    "type": "integer"
                },
                "outInterface": {
                    "type": "string"
                },
                "service": {
                    "type": "string"
                },
                "srcAddress": {
                    "type": "string"
                },
                "srcZone": {
                    "$ref": "#/definitions/sentinelos_core_internal_model.Zone"
                },
                "translatedIP": {
                    "type": "string"
                },
                "translatedPort": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/sentinelos_core_internal_model.NATType"
                }
            }
        },
        "sentinelos_core_internal_model.NATType": {
            "type": "string",
            "enum": [
                "snat",
                "dnat-ip",
                "dnat-port"
            ],
            "x-enum-varnames": [
                "TypeSNAT",
                "TypeDNATIP",
                "TypeDNATPort"
            ]
        },
        "sentinelos_core_internal_model.Policy": {
            "type": "object",
            "properties": {
                "action": {
                    "$ref": "#/definitions/sentinelos_core_internal_model.Action"
                },
                "dstAddr": {
                    "$ref": "#/definitions/sentinelos_core_internal_model.Address"
                },
                "dstZone": {
                    "$ref": "#/definitions/sentinelos_core_internal_model.Zone"
                },
                "id": {
                    "type": "integer"
                },
                "log": {
                    "type": "boolean"
                },
                "services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sentinelos_core_internal_model.Service"
                    }
                },
                "srcAddr": {
                    "$ref": "#/definitions/sentinelos_core_internal_model.Address"
                },
                "srcZone": {
                    "$ref": "#/definitions/sentinelos_core_internal_model.Zone"
                }
            }
        },
        "sentinelos_core_internal_model.Protocol": {
            "type": "string",
            "enum": [
                "tcp",
                "udp"
            ],
            "x-enum-varnames": [
                "TCP",
                "UDP"
            ]
        },
        "sentinelos_core_internal_model.Route": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "gateway": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "interface": {
                    "type": "string"
                },
                "metric": {
                    "type": "integer"
                }
            }
        },
        "sentinelos_core_internal_model.Service": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "ports": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "protocol": {
                    "$ref": "#/definitions/sentinelos_core_internal_model.Protocol"
                }
            }
        },
        "sentinelos_core_internal_model.Vlan": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "ip": {
                    "type": "string"
                },
                "management": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "parent": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "zone": {
                    "type": "string"
                }
            }
        },
        "sentinelos_core_internal_model.Zone": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "interfaces": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "networks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "$ref": "#/definitions/sentinelos_core_internal_model.ZoneType"
                }
            }
        },
        "sentinelos_core_internal_model.ZoneType": {
            "type": "string",
            "enum": [
                "l2",
                "l3"
            ],
            "x-enum-varnames": [
                "ZoneL2",
                "ZoneL3"
            ]
        },
        "sentinelos_core_internal_system.InterfaceInfo": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string"
                },
                "management": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "zone": {
                    "type": "string"
                }
            }
        },
        "sentinelos_core_pkg_utils.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "SentinelOS API",
	Description:      "Next-Generation Firewall Management API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
